### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by dolevp** [LilyFoote/rest-framework-generic-relations#56]
Please consider adding a license

**Comment by craigds** [comment]
I'd suggest a [BSD 3-clause license.](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)

If @Ian-Foote's okay with that, I'll add it.

**Comment by Ian-Foote** [comment]
The code originated in https://github.com/encode/django-rest-framework/pull/755. If a BSD 3-clause license is compatible with that, go for it!

**Comment by craigds** [comment]
IANAL but I expect the original code from that PR would have been implicitly licensed under BSD 3-clause license since that's the license DRF uses.

@lukasbuenger are you okay with us applying a BSD 3-clause license to this codebase?
